version: '3.7'
services:
  blockchain-price-tracker:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_USER=user
      - DATABASE_PASSWORD=pass
      - DATABASE_NAME=prices
    depends_on:
      - database

  database:
    image: postgres:13  # You can specify the version explicitly
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: prices
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
